version: '2'

services:
  pod_network:
    image: k8s.gcr.io/pause-amd64:3.1
    ports:
      - "127.0.0.1:16432:5432"
      - "127.0.0.1:19127:9127"
  pgbouncer:
    build:
      context: ../.
      dockerfile: ./docker/Dockerfile.pgbouncer
    image: pgbouncer
    volumes:
      - "../tests/environment/pgbouncer:/etc/pgbouncer"
      - "../tests/environment/userlist:/etc/userlist"
    network_mode: "service:pod_network"
  pg:
    image: postgres:9.6-alpine
    restart: always
    volumes:
      - "../tests/environment/pg:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "127.0.0.1:15432:5432"
  control:
    depends_on: ["pgbouncer"]
    image: pgbouncer
    volumes:
      - "../tests/environment/pgbouncer:/etc/pgbouncer"
      - "../tests/environment/userlist:/etc/userlist"
    environment:
      CONFIG_PATH: /etc/pgbouncer
      PGBOUNCER_HOST: 127.0.0.1
      PGBOUNCER_PORT: 5432
      PGBOUNCER_USER: admin
      PGBOUNCER_PASSWORD: xaod4yeeS5ohsh7chaesh0Quichauv8o
      LOG_JSON: 1
    entrypoint: python
    command: "/opt/configmap-reload.py -vv"
    network_mode: "service:pod_network"
  exporter:
    depends_on: ["pgbouncer"]
    image: spreaker/prometheus-pgbouncer-exporter:2.0.1
    environment:
      PGBOUNCER_PORT: 5432
      PGBOUNCER_USER: admin
      PGBOUNCER_PASS: xaod4yeeS5ohsh7chaesh0Quichauv8o
      PGBOUNCER_EXPORTER_HOST: 0.0.0.0
    network_mode: "service:pod_network"
